### ISSUE TITLE
Keypoint format

### ISSUE THREAD

**Issue by yukichou** [Walter0807/MotionBERT#10]
I get the coco 17 key-points or any other key-point format of my own custom data, and I know I should convert the coco format to human3.6, but how? The definition between coco and human 3.6 is different especially for the body. Is there any way to convert the format between these datasets?

**Comment by Serdnad** [comment]
The `lib/data/dataset_action.py` has a `coco2h36m` function that accepts a numpy ndarray of keypoints and does a rough conversion to the human3.6m format. I think I've seen other projects take a similar approach.

**Comment by yukichou** [comment]
> The `lib/data/dataset_action.py` has a `coco2h36m` function that accepts a numpy ndarray of keypoints and does a rough conversion to the human3.6m format. I think I've seen other projects take a similar approach.

Thank you so much ! I will check this out, as soon as possible.

**Comment by vicentowang** [comment]
pose track and coco ,human3.6 ,AMASS ,there are all have different keypoints style, how to get unified keypoints ?

**Comment by RHnejad** [comment]
On the other hand the original Cascaded Pyramid Network uses COCO format and the fine-tuned version which was available was H3.6 format. I was wondering whether there is documentation available somewhere about how they fine-tune CPN. Thanks :)
