### ISSUE TITLE
Overlaying mesh over image

### ISSUE THREAD

**Issue by take2rohit** [Walter0807/MotionBERT#101]
Thanks for the awesome work and code. I wanted to know how can we project/overlay the SMPL vertices over the image, just like other papers like BEDLAM. This will show exactly how well the SMPL vertices are for an Image.
Currently, I see that the code makes an arbitrary-size canvas and does projection over it. However, I want to project and align exactly with the image.

Any guidance would be greatly appreciated

**Comment by Walter0807** [comment]
Thanks for your interest! You will need camera parameters to do pixel-aligned projection, which is difficult to estimate from skeletons alone. However, you can obtain them from other RGB-based mesh recovery methods.
