### ISSUE TITLE
About global root transl

### ISSUE THREAD

**Issue by mziyuu** [Walter0807/MotionBERT#103]
Hi, thanks for the amazing work!

I run `infer_wild_mesh.py` and use J_regressor in SMPL_NEUTRAL.pkl to get 24 joints psitions, the performance is great, but the root seems to be fixed at about (0, 0, 0). If I want to get joint positions in global corridnate, should I run `infer_wild.py` and select the root position as global transl?

**Comment by Walter0807** [comment]
Thanks for your interest in our work. Yes, this is the logistics in the provided demo.
