### ISSUE TITLE
A question for train_mesh.py

### ISSUE THREAD

**Issue by lllluy** [Walter0807/MotionBERT#105]
Hi
I'm trying to retrain a human mesh model using my own dataset, and I've encountered some difficulties. 

While examining the "mesh_det_h36m.pkl" data you provided, I noticed there are eight fields, and I'm particularly interested in understanding how "smpl_pose" and "smpl_shape" are computed. Could you please explain how these values are calculated? 

Alternatively, if I already have "joint_2d" and "joint_cam" data, how can I compute the corresponding "smpl_pose" and "smpl_shape"?

I appreciate your assistance. Looking forward to your reply.

**Comment by ShirleyMaxx** [comment]
Hi, 
The `smpl_pose` and `smpl_shape` are SMPL parameters, which are provided officially by the Human3.6M dataset.

If you already have `joint_2d` and `joint_cam` data, you may consider using [SMPLify](https://people.eecs.berkeley.edu/~kanazawa/papers/SMPLify.pdf) or other recent works to optimize and get pseudo-GT SMPL parameters.
