### ISSUE TITLE
about world coordinate 3d data

### ISSUE THREAD

**Issue by soobinseo** [Walter0807/MotionBERT#109]
Thank you for providing the excellent code. 

I have a question about the H36M 3D data. I noticed that the root's z-values are all set to 0 from the preprocessed 3d data. 
Does this mean that the poses are estimated in a coordinate system with the root at z=0? 
If so, Is there any data available that predicts the actual 3D joint positions in world coordinates including camera information?

**Comment by Walter0807** [comment]
Thanks for your interest in our work. Predicting absolute depth from monocular images can be ambiguous, especially using only 2D pose as input. For this line of work, you can check [VirtualPose](https://github.com/wkom/VirtualPose).
