### ISSUE TITLE
PyTorch version for reproducing the result

### ISSUE THREAD

**Issue by flyyyyer** [Walter0807/MotionBERT#11]
I want to reproduce the result of "3D Pose (H36M-SH, scratch), 39.1mm", but I only can get 40.0mm.  So I want to know what is the  PyTorch version you used to train the model?

**Comment by HoBeom** [comment]
Did you adjust batch_size and learning_rate in the code?
Using the most recent PyTorch for the installation guide seems to be recommended.

**Comment by flyyyyer** [comment]
I change the batch_size from 32 to 4 and 8, because I only have one 3090 GPU with 24GB.

**Comment by Walter0807** [comment]
Hi, if you change the batch size, you may need to adjust the lr accordingly. Thank you @HoBeom for pointing out!
