### ISSUE TITLE
i had some weird result in rendering

### ISSUE THREAD

**Issue by noah0924** [Walter0807/MotionBERT#112]
Hi, I appreciate for your great contributions.

I followed the colab version of #68 

This is my 2D prediction.

![image](https://github.com/Walter0807/MotionBERT/assets/152379145/8661af7a-ffc9-4774-9235-1a2707340862)

But 3D rendering result is this.

![image](https://github.com/Walter0807/MotionBERT/assets/152379145/12b45613-7e46-41cf-a4ff-04ebd56d5b4d)

Some keypoints are fixed on the left top location

Here is another one for another video.

![image](https://github.com/Walter0807/MotionBERT/assets/152379145/e630898f-c080-4577-847e-195da7b3673b)

I think 2D pose doesn't have any problem.

How could I fix this problem?

**Comment by NigelHiggs30** [comment]
@noah0924 What exact line changes did you make? I thought I made the correct line changes here
 ```%cd /content/AlphaPose
# the vid filename copied earlier..
vid_ff = "/content/test2.mp4" # place it here

!python3 scripts/demo_inference.py --cfg configs/halpe_26/resnet/256x192_res50_lr1e-3_1x.yaml --checkpoint pretrained_models/halpe26_fast_res50_256x192.pth --indir examples/res/vis --video {vid_ff} --save_video
``` 


but I still got the same output as above.

**Comment by phsilvarepo** [comment]
Same here, Any solutions? Which weights or config files should I use? @noah0924 @NigelHiggs30 

Solution: Had to do a full reset of the notebook, trying to run the model with changes without clearing the folders produced same results, not sure why but yeah...
