### ISSUE TITLE
keypoint_score in dataset_action.py

### ISSUE THREAD

**Issue by fneaplle** [Walter0807/MotionBERT#132]
Hello. Thank you for your research. 

While applying your research to my data, I discovered a problem.

https://github.com/Walter0807/MotionBERT/blob/1839f099ce9f128342c8f5499478ace328c0df4a/lib/data/dataset_action.py#L152

I think 
`motion_conf = sample['keypoint_score[..., None]']` should be changed to `motion_conf = coco2h36m(sample['keypoint_score[..., None]'])` (line 152 in dataset_action.py)

Could you please check if what I thought is correct? @Walter0807

**Comment by Walter0807** [comment]
Seems like a good catch. Feel free to open a PR if you want. It would also be great if you can report the performance after fix!

**Comment by fneaplle** [comment]
Can I close this issue? After conducting the experiment, I will post a PR with performance report. Thank you for answer
