### ISSUE TITLE
Can I inference with camera

### ISSUE THREAD

**Issue by NNLong1208** [Walter0807/MotionBERT#15]
How can I run the model with image

**Comment by Walter0807** [comment]
You can treat images as length=1 videos. Please refer to [docs/inference.md](https://github.com/Walter0807/MotionBERT/blob/main/docs/inference.md) for guidance.

**Comment by MikeHubXP** [comment]
Hi, in the 
[https://github.com/Walter0807/MotionBERT/blob/main/docs/inference.md] i dont se a guidance to how to make the input to be a image file, when i try to specify --vid_path to point to .jpg file and setting the --clip_len to 1, it still does not work. Could you help or guide me somehow?

Thanks.
