### ISSUE TITLE
In-the-wild Inference input format

### ISSUE THREAD

**Issue by RHnejad** [Walter0807/MotionBERT#16]
Hello and thanks for sharing your code.
May I please ask about the structure of the .json file needed for the In-the-wild Inference for 3D pose estimation? I want to use 2d estimations of another network other than AlphaPose and was not sure how to structure my 2d poses so it's compatible with your code.
Thanks in advance for your help.

**Comment by fan23j** [comment]
This worked for me:

`
[
    {
        "image_id": "0.jpg",
        "category_id": 1,
        "keypoints": [
            557.1444091796875, 734.3290405273438, 0.5740299224853516,
            ...
        ],
        "score": 1.8695456981658936
    },
    {
        "image_id": "1.jpg",
    ...
`

Where each entry to the json represents a prediction frame. Since the authors convert halpe to h36m, the keypoints entry is length 78 (26 x [x,y,score]).

**Comment by RHnejad** [comment]
> This worked for me:
> 
> `[ { "image_id": "0.jpg", "category_id": 1, "keypoints": [ 557.1444091796875, 734.3290405273438, 0.5740299224853516, ... ], "score": 1.8695456981658936 }, { "image_id": "1.jpg", ...`
> 
> Where each entry to the json represents a prediction frame. Since the authors convert halpe to h36m, the keypoints entry is length 78 (26 x [x,y,score]).


Thank you very much for your answer. 

About the entry length, do you know whether they do the conversion before running infer_wild.py, or it is supposed to be embedded in the code, cause I did not find anywhere in their code that [halpe2h36m()](https://github.com/Walter0807/MotionBERT/blob/c5db08c5ffaf3027a8a2f9ff465449d1e0b6d7e4/lib/data/dataset_wild.py#:~:text=def-,halpe2h36m,-(x)%3A) is being called. As my keypoint is already being converted to h3.6 from coco I wanted to check whether I can use 17 * [x,y,score].

**Comment by ywdong** [comment]
it's quite hard for me to install alphapose, can't it be any other 2d pose estimation model?

**Comment by fan23j** [comment]
Any pose estimation model should work as long as you properly format the output json. I personally used yolov5 + ViTPose topdown pipeline.

**Comment by ywdong** [comment]
> Any pose estimation model should work as long as you properly format the output json. I personally used yolov5 + ViTPose topdown pipeline.
Hi，fan23j，Can u share me your script how to use the vitpose output to generate the input format？Thx

**Comment by fan23j** [comment]
> > Any pose estimation model should work as long as you properly format the output json. I personally used yolov5 + ViTPose topdown pipeline.
> > Hi，fan23j，Can u share me your script how to use the vitpose output to generate the input format？Thx

sure give me some time to upload to github

**Comment by fan23j** [comment]
> 
Here you go. Let me know if you run into any issues. 
https://github.com/fan23j/yolov5-vitpose-video-annotator

**Comment by Walter0807** [comment]
> Any pose estimation model should work as long as you properly format the output json. I personally used yolov5 + ViTPose topdown pipeline.

That's correct, thanks Jack! For other 2D pose estimators (and keypoint formats), you only need to change line68-line77 in https://github.com/Walter0807/MotionBERT/blob/main/lib/data/dataset_wild.py (read the 2D results and convert to H36M format). 

Let me know if you have further questions.

**Comment by TOWHIDCSE4** [comment]
Hi Jack,

That's correct, thank you for the clarification!

To adapt other 2D pose estimators and their keypoint formats, you only need to modify lines 68 to 77 in the following file: [dataset_wild.py](https://github.com/Walter0807/MotionBERT/blob/main/lib/data/dataset_wild.py). Specifically, you will need to read the 2D pose results and convert them into the H36M format.

Thanks again for your interest in our work! Please don't hesitate to reach out if you have any further questions or need additional clarification.

**Comment by TOWHIDCSE4** [comment]
Hi @Walter0807  May I please ask about the structure of the .json file needed for the In-the-wild Inference for 3D pose estimation?
I already got json data from AlphaPose . 
but motionbert wild Inference i get error in json format .
"IndexError: index 19 is out of bounds for axis 1 with size 17"
how can fix it ? please give me soluation.
![image](https://github.com/user-attachments/assets/641ae37e-c797-44ae-844a-d359dcee6c23)
