### ISSUE TITLE
Can you provide pre-train model with smaller sequence length (e.g.: 27, 81) ?

### ISSUE THREAD

**Issue by Zhenghongwei0929** [Walter0807/MotionBERT#17]
The 243-length model training is too much computational and memory consumption for me. Can you provide pre-train model with a smaller sequence length (e.g.: 27, 81)? Thanks!

**Comment by Walter0807** [comment]
Hi, you can use the 243-frame model with a smaller input length (even 1), that's fine. You may also want to use the MB-lite pretrained model or decrease the batch size for finetuning.
