### ISSUE TITLE
Mesh with HybrIK 

### ISSUE THREAD

**Issue by zhengchangren95** [Walter0807/MotionBERT#19]
Will you provide the code of mesh recovery using HybrIK (report in Table 3)? I’d appreciate it if you can release the code related to this part.

**Comment by Walter0807** [comment]
Hi, we created a branch for the refiner module. You can follow the instructions here: https://github.com/Walter0807/MotionBERT/blob/refine/docs/mesh.md#refiner.

**Comment by zhengchangren95** [comment]
Really appreciate! Hoping to see the related code (such as the refiner code, train_mesh_refine.py, MB_ft_pw3d_refine_hybrik.yaml, etc... ) soon!

**Comment by Walter0807** [comment]
> Really appreciate! Hoping to see the related code (such as the refiner code, train_mesh_refine.py, MB_ft_pw3d_refine_hybrik.yaml, etc... ) soon!

No problem, you can find them in the 'refine' branch.

**Comment by zhengchangren95** [comment]
Oh I see, great thx. Amazing works!

**Comment by tszhang97** [comment]
@Walter0807 Hi, I read the code and cannot find the computation of  "residual in joint rotations" in the branch "refine". The MeshRegressor() directly regresses the 'theta' and MeshLoss() computes the pose loss. So, I'm wondering where to compute "residual in joint rotations"? Hope to get your reply, thanks a lot!
