### ISSUE TITLE
some train questions

### ISSUE THREAD

**Issue by XuchaoLiu-HEU** [Walter0807/MotionBERT#2]
Thanks for your great work! I have some questions about how this Dual-stream Spatio-temporal Transformer (DSTformer) can accelerate training in parallel. Besides, whether is T=243 too computationally intensive  for T-MHSA.
![image](https://user-images.githubusercontent.com/53993706/196874932-8a9e0580-0937-49ab-be75-32e6110d5d87.png)
Thank you very much!

**Comment by Walter0807** [comment]
Hi, thanks for your interest in our work. 
1. Parallel training is mainly backed by the parallelization of self-attention operations of the Transformer.
2. We find the speed/memory cost OK in our experiments. During finetuning, you can use smaller temporal lengths and still benefit from the pretrained model.
