### ISSUE TITLE
How to accelerate model infer speed

### ISSUE THREAD

**Issue by ywdong** [Walter0807/MotionBERT#20]
Hi，I use the script ‘infer_wild.sh’ to infer 3d pose. I have a gpu and can I use it or use other method to accelerate model rendering speed? I found the the GPU utilization rate is very low.
![image](https://user-images.githubusercontent.com/1457889/231110098-cc93720c-e181-476f-87f6-292d04e4c37c.png)

**Comment by ywdong** [comment]
> Hi, it first does model inference (GPU by default), then render the frames (CPU). Which one is your speed bottleneck?
The first one，I just want to increase the batch_size in the script
`testloader_params = { 
          'batch_size': 1,
          'shuffle': False,
          'num_workers': 8,
          'pin_memory': True,
          'prefetch_factor': 4,
          'persistent_workers': True,
          'drop_last': False
}`
but I got the error. Can u have any idea?

**Comment by Walter0807** [comment]
Model inference should be very fast and it uses GPU by default. Maybe you can post your terminal outputs with the speed.

**Comment by Walter0807** [comment]
In this case, you can increase batch_size or clip_len.

**Comment by RHnejad** [comment]
I realized the video rendering is the bottleneck so by commenting video rendering part of the inference code, I achieved a fast performance.
