### ISSUE TITLE
InstaVariety 2D keypoints preprocess

### ISSUE THREAD

**Issue by JiahongWu1995** [Walter0807/MotionBERT#22]
Hello, how do I generate the motion_all. npy and id_all. npy from the training dataset InstaVariety?
 Not found on the page https://github.com/Walter0807/MotionBERT/blob/main/docs/pretrain.md thank you!

**Comment by Walter0807** [comment]
Hi, thanks for your message. We have updated the docs and provide the files. Please check again.

**Comment by JiahongWu1995** [comment]
thank you!
