### ISSUE TITLE
About Amass trainset

### ISSUE THREAD

**Issue by JiahongWu1995** [Walter0807/MotionBERT#27]
Hello, may I ask if the GRAB and SOMA in the AMASS training set are not used in the training of the pre trained model? If they are used, code tools/compress_amass.py seems to be incorrect?

**Comment by JiahongWu1995** [comment]
The GRAB and SOMA do not have data with key 'dmpl'.
https://github.com/Walter0807/MotionBERT/blob/64fef16902803e3bebafbdecb905d527eda676f8/tools/compress_amass.py#L42

**Comment by Walter0807** [comment]
Thanks for your message. We accessed the dataset about 1 year ago, and process them with the scripts. Since they released new data constantly, you may need to process them by yourself if the format is different. It should not  be too difficult to render the SMPL and map them to skeletons.

**Comment by JiahongWu1995** [comment]
thank you!
