### ISSUE TITLE
Real time application

### ISSUE THREAD

**Issue by blazapropeler** [Walter0807/MotionBERT#29]
Hi!

I was just wondering if you have some results on the speed and if this model (in the Lite variant) would be suitable for a real-time 3d pose estimation problem?

Thanks

**Comment by Walter0807** [comment]
We have not tested the speed, but from my experience the inference is very fast with GPU. It seems like real-time works from this [issue](https://github.com/Walter0807/MotionBERT/issues/28).

**Comment by lucasjinreal** [comment]
I have tested the pose3d, it was extremly fast. However I found the mesh3d model ran twice in infer_wild_mesh file. @Walter0807  Do u know how much effect loose if we just using single forward on mesh3d inference?

**Comment by XALEX-123** [comment]
hello @lucasjinreal, I recently try to inference motionbert in real time, but i'm stuck. Now I can use AlphaPose to do 2D extraction in real time, however, i don't know how to use this real time 2D extraction as an input to the motionbert, can you guide me or give me some advice? thank you so much!

**Comment by lucasjinreal** [comment]
@XALEX-123 Actually I found motionBert has large performance reduce if you are not sampling on whole sequence, you should try on python first, take a deep look at performance in realtime situation.

**Comment by XALEX-123** [comment]
@lucasjinreal thank your rapid reply, then how can i inference motionbert in real time?

**Comment by luoww1992** [comment]
@lucasjinreal 
can your share your main env and GPU on your PC, how many fps ?

**Comment by ailettuce80** [comment]
> [@XALEX-123](https://github.com/XALEX-123) Actually I found motionBert has large performance reduce if you are not sampling on whole sequence, you should try on python first, take a deep look at performance in realtime situation.

Did you ever measure the performance?
