### ISSUE TITLE
hello, does the MAED mesh head included in code mentioned in paper?

### ISSUE THREAD

**Issue by lucasjinreal** [Walter0807/MotionBERT#30]
hello, does the MAED mesh head included in code mentioned in paper?

**Comment by Walter0807** [comment]
Hi, do you mean [this part](https://github.com/Walter0807/MotionBERT/issues/19)?

**Comment by lucasjinreal** [comment]
@Walter0807 Actually I am not a fan of hybrik, it's just tooo complicated, I remember you have compared 2 heads SPIN, MAED, Hybrik, I passsed hybrik at first, does MAED is the default implement in current mesh model? But it looks like SPIN. And the MPAJE in readme looks not same in paper.

**Comment by Walter0807** [comment]
We treat the three other methods in the same manner for the refiner module (regress a residual in joint rotations).

**Comment by lucasjinreal** [comment]
Thanks, from the refiner branch, it seems the head a little bit different, but can't tell which part specificly denotes to MAED head.

**Comment by Walter0807** [comment]
We do not have a specific MAED head; instead, we use our method as a plug-in into RGB-based methods as shown [here](https://github.com/Walter0807/MotionBERT/blob/refine/lib/model/model_mesh_refine.py#L29).

**Comment by lucasjinreal** [comment]
thanks, whats the mainly difference between model_mesh_refiner and model_mesh, it looks like very identical
