### ISSUE TITLE
About the conf input

### ISSUE THREAD

**Issue by lucasjinreal** [Walter0807/MotionBERT#32]
Hello, I notice that the input can be with or without conf, but didn't saw any ablation on this part, if it uses conf, then it highly couple with the pose model itself (some models might didn't produce relatively high scores), does there any add conf or not the final metrices accordingly?

**Comment by Walter0807** [comment]
We use confidence mainly because it allows the masking operation more easily. You can also set all confidence=1.00 if you want.
