### ISSUE TITLE
About Preprocessing

### ISSUE THREAD

**Issue by lucasjinreal** [Walter0807/MotionBERT#33]

**Comment by Walter0807** [comment]
I'm not sure, what is wrong with your result? You can also print the variables (e.g. network input) in C++ and python.

**Comment by lucasjinreal** [comment]
@Walter0807 the output of onnx is same with pytorch when feeding same input. As I should feed the keypoints and process in c++, so I doubt is this preprocess keypoints part not fully aligned with python. however it's hard to compare the values in c++ but if onnx is right, then wrong part must be some preprocessing step.

**Comment by lucasjinreal** [comment]
@Walter0807  I realize the problem, it seems original python have 2 ways for normalize, using input w h or directly normalize to -1, 1, what's the differences between them?

**Comment by lucasjinreal** [comment]
I have resolved all problems, not C++ runs OK.
