### ISSUE TITLE
mesh prediction error 

### ISSUE THREAD

**Issue by hhy-joseph** [Walter0807/MotionBERT#35]
I run this code:
!python3 infer_wild_mesh.py --vid_path ./4.mp4 --json_path ./alphapose-results.json --out_path /content/MotionBERT 

I have saved the best_epoch here:
/content/MotionBERT/checkpoint/mesh/FT_MB_release_MB_ft_pw3d/best_epoch.bin

Traceback (most recent call last):
  File "/content/MotionBERT/infer_wild_mesh.py", line 64, in <module>
    smpl = SMPL(args.data_root, batch_size=1).cuda()
  File "/content/MotionBERT/lib/utils/utils_smpl.py", line 62, in __init__
    super(SMPL, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/smplx/body_models.py", line 133, in __init__
    assert osp.exists(smpl_path), 'Path {} does not exist!'.format(
AssertionError: Path data/mesh does not exist!

**Comment by ShirleyMaxx** [comment]
Hi, please first download the data and put them to `data/mesh` following the [instruction](https://github.com/Walter0807/MotionBERT/blob/main/docs/mesh.md#data).

**Comment by manu13008** [comment]
Hi,
Sorry to re-open the issue but 2 issues here : 
1. According to the readme inference, they never say to donwload the files to do the mesh inference. Then, why would we need it ?
2. I tried to find the basicModel_neutral_lbs_10_207_0_v1.0.0.pkl file, with no success. Anyone could tell me where this file is ?

Thanks!

**Comment by ShirleyMaxx** [comment]
Hi, thank you for your interest.

1. Apologies for not mentioning the need to download the file in the inference README. We’ll update it accordingly. However, as of now, you do need to follow the [instructions](https://github.com/Walter0807/MotionBERT/blob/main/docs/mesh.md#data) to download the required data before running the inference correctly.
2. As mentioned in the [instructions](https://github.com/Walter0807/MotionBERT/blob/main/docs/mesh.md#data), please visit [SMPLify](https://smplify.is.tue.mpg.de/) and download the "Code and model." After extracting the files, you will find the required `.pkl` file there.
