### ISSUE TITLE
The formula notation in the paper

### ISSUE THREAD

**Issue by Ared521** [Walter0807/MotionBERT#37]
Thank you for your great work, and I have a question about one of the formulas in the paper. ◦ denotes element-wise production. But I didn't know ◦, what that symbol meant, could you tell me about it ?

**Comment by Walter0807** [comment]
You can check this: https://en.wikipedia.org/wiki/Hadamard_product_(matrices)

**Comment by Ared521** [comment]
> You can check this: https://en.wikipedia.org/wiki/Hadamard_product_(matrices)

Thank you for your reply. I am a novice and this is very helpful. Thank you.
