### ISSUE TITLE
About half body mesh regression issue

### ISSUE THREAD

**Issue by lucasjinreal** [Walter0807/MotionBERT#38]
Hello, I recently found mb seems not very good at half body mesh regression, just wonder if you have tested it before and what could be  the reason caused this?

for image based model like PARE, SPIN, it can imaginary on blinded part, but for mb, it totally failed at this scene.

**Comment by ShirleyMaxx** [comment]
Hi, thanks for your interest. 

Could you provide more details of what the input of the half-body 2D motion is to MB?

**Comment by lucasjinreal** [comment]
i.e. only upper body visible, the mesh output is wrong (might caused by keypoints not stable)

**Comment by Walter0807** [comment]
We did not use data augmentations as image-based methods when fine-tuning mesh estimation, e.g. adding occlusion and cropping, which makes half-body estimation more robust.

If you wish to use MB under these cases, you can add these augmentations (e.g. randomly mask half-body joints) when fine-tuning. You can also you MB as a refiner to image-based approaches as discussed in the paper.

**Comment by Walter0807** [comment]
How you treat the invisible keypoints in 2D results also matters. It should be set to low confidence value (or compeletely zeroed out), similar to the masking operation.

**Comment by lucasjinreal** [comment]
@Walter0807 does it pratical if score under some threshold, set xyscore all to zeros? we can only judge keypoints is invalid or not by score threshold in real life.

**Comment by Walter0807** [comment]
I think it depends on your 2D estimator. You can check its output given the half-body images. Also, if half-body is an important case for you, you can try fine-tuning with this specific data augmentation.
