### ISSUE TITLE
wild video infer too slow

### ISSUE THREAD

**Issue by Ared521** [Walter0807/MotionBERT#41]
Hello, may I ask, I deduce that my own video speed is very slow, 10s video takes more than ten minutes, and there are some warning messages, may I ask why?

MAGEIO FFMPEG_WRITER WARNING:  input image is not divisible by macro_block_size=16, resizing from (923, 924) to (928,  928) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisib

le by the macro_block_size or set the macro_block_size to 1 (risking incompatibility).

0% | ▋ | 1/296 [00:00 & lt; 04:16, 1.15 it/s] [

swscaler @ 000001df1adc4300] Warning: data is not aligned!  This can lead to a speed loss

My testloader Settings are as follows: testloader_params = {

'batch_size': 1,

'shuffle': False,

'num_workers': 0,

'pin_memory': True,

'prefetch_factor': 2,

'persistent_workers': False,

'drop_last': False

}

**Comment by Ared521** [comment]
> I recall running into this issue as well. In my case, my gpu memory was being occupied but my gpu utilization was still 0%. Could you check your `nvidia-smi` output? I never explored further to debug my issue, but hopefully this gives you some insight to check your installation / setup or the gpu utilization in the scripts.

Thanks for your reply. I found the infer speed was very fast, and the main time was spent on render

**Comment by luoww1992** [comment]
@Ared521 ,
i have same question, how to solve, what is your env and gpu , how many fps ? my GPU is 2080ti, should i change it ?

**Comment by baitian752** [comment]
@luoww1992  #102 maybe fix  render is too slow
