### ISSUE TITLE
Input keypoint structure

### ISSUE THREAD

**Issue by jlnk03** [Walter0807/MotionBERT#44]
Hi, the documentation says to use the H36M keypoint format or the Halpe 26 keypoints. Since these two formats differ and I’m trying to use YOLOv7 to extract the 2D poses, which keypoints and ordering does MotionBERT expect? Is there an example json available? Thank you😊

**Comment by XALEX-123** [comment]
Each input format should be alright, because you can map any keypoint into the other one in the data/dataset_wild.py

**Comment by Walter0807** [comment]
Thanks @XALEX-123.
Here is an example json file in AlphaPose output format. [sample.zip](https://github.com/Walter0807/MotionBERT/files/11526727/sample.zip)

**Comment by jlnk03** [comment]
Thanks to both of you! This helped a lot :)
