### ISSUE TITLE
About evaluate function during training

### ISSUE THREAD

**Issue by tszhang97** [Walter0807/MotionBERT#48]
Hi, I use the training code and find something wrong. 
https://github.com/Walter0807/MotionBERT/blob/ec48976542ba746fd1b48054502be03888fbab86/train.py#LL340C89-L340C89 The test dataloader include AMASS, and in dataset_motion_3d.py, 2d input use motion_file['data_input'] which is None when generating AMASS testset. So, how to use AMASS testset or just use H3.6M testset？ Looking forward to your reply, thx!
![image](https://github.com/Walter0807/MotionBERT/assets/39046939/42bbf521-d97e-43d9-ad44-a750bf856ff5)
![image](https://github.com/Walter0807/MotionBERT/assets/39046939/4b307df9-6c2d-4eca-9494-11f53e5e5d0f)

**Comment by Walter0807** [comment]
Hi, we use AMASS for pretraining, and no AMASS data is used for testing. The test loader should contain H36M motion only.
