### ISSUE TITLE
Finetune data format

### ISSUE THREAD

**Issue by XALEX-123** [Walter0807/MotionBERT#49]
hello @Walter0807 , I wanna finetune pose3d task for my own dataset, what data format should I prepare, like what's inside .pkl file. Now I have a 2D skeleton video and the json file from Alphapose, what should I do next.
Sorry for keeping bothering you.

**Comment by Walter0807** [comment]
Hi, do you want to finetune on a 2D dataset or inference on your own videos with 2D pose estimation results?

**Comment by XALEX-123** [comment]
I want to finetune the process of lifting 2D to 3D I have Azure Kinect so I can create the 3D ground truth on my own. However, I don't know those number in .pkl mean, can you share some information to me? That's will be a huge help, thanks!!

**Comment by Walter0807** [comment]
You can check the data processing part in [LCN](https://github.com/CHUNYUWANG/lcn-pose#data). Basically, you need to align 3D GT and 2D detections in the pixel coordinates so that you can finetune the 2D->3D mapping.
