### ISSUE TITLE
What is 2.5d_factor in preprocessed H3.6M data?

### ISSUE THREAD

**Issue by LareinaM** [Walter0807/MotionBERT#51]
Hi, I looked through LCN and all data processing scripts, but none of them ever mentioned 2.5d-related fields. I wonder how is `2.5d_factor` in the pkl file is calculated?

**Comment by Walter0807** [comment]
I think it's on their T-PAMI version section 6.2.2. Basically, it's just a normalizing factor between pixel coordinates and the world coordinates.

**Comment by LareinaM** [comment]
> I think it's on their T-PAMI version section 6.2.2. Basically, it's just a normalizing factor between the pixel coordinates and the world coordinates.

I read through that section, but it actually explains your `DataReaderH36M` section. I wonder how to obtain that factor, as it does not appear in any code scripts.

**Comment by Walter0807** [comment]
> > I think it's on their T-PAMI version section 6.2.2. Basically, it's just a normalizing factor between the pixel coordinates and the world coordinates.
> 
> Hi @Walter0807, I read through that section, but it actually explains your `DataReaderH36M`. I wonder how to obtain that factor, as it does not appear in any code scripts, thx!

Sorry, it should be in Section 6.2.1 (LCN, PAMI 2020).
<img width="537" alt="image" src="https://github.com/Walter0807/MotionBERT/assets/25319568/a4a25bad-e323-4963-9c33-bc7512218d3a">
The 2.5d factor is the $lambda$ here.

**Comment by LareinaM** [comment]
> > > I think it's on their T-PAMI version section 6.2.2. Basically, it's just a normalizing factor between the pixel coordinates and the world coordinates.
> > 
> > 
> > Hi @Walter0807, I read through that section, but it actually explains your `DataReaderH36M`. I wonder how to obtain that factor, as it does not appear in any code scripts, thx!
> 
> Sorry, it should be in Section 6.2.1 (LCN, T-PAMI 2020). <img alt="image" width="537" src="https://github.com/Walter0807/MotionBERT/assets/25319568/a4a25bad-e323-4963-9c33-bc7512218d3a"> The 2.5d factor is the λ here.

Thanks for your reply! I wonder if there is any code related to this part, it's very hard to infer by oneself.

**Comment by Walter0807** [comment]
Sorry, I did not implement this part, the processed data was from LCN. If you have the original H36M data, you can estimate the corresponding $\lambda$ as described.

**Comment by LareinaM** [comment]
> Sorry, I did not implement this part, the processed data was from LCN. If you have the original H36M data, you can estimate the corresponding λ as described.

Thanks for replying! From my understanding, in data processing script of lcn, `joint_3d_image` is `P_p` and `joint_3d_camera` is `P_c`, which should be root-centered and then used to calculate λ. When I tried using the above approach, the result is not the `2.5d_factor`.

**Comment by Walter0807** [comment]
> > Sorry, I did not implement this part, the processed data was from LCN. If you have the original H36M data, you can estimate the corresponding λ as described.
> 
> Thanks for replying! From my understanding, in data processing script of lcn, `joint_3d_image` is `P_p` and `joint_3d_camera` is `P_c`, which should be root-centered and then used to calculate λ. When I tried using the above approach, the result is not the `2.5d_factor`.

Is the result close or not? I did not go into the code details of LCN, perhaps you can leave an issue there.

**Comment by LareinaM** [comment]
> > > Sorry, I did not implement this part, the processed data was from LCN. If you have the original H36M data, you can estimate the corresponding λ as described.
> > 
> > 
> > Thanks for replying! From my understanding, in data processing script of lcn, `joint_3d_image` is `P_p` and `joint_3d_camera` is `P_c`, which should be root-centered and then used to calculate λ. When I tried using the above approach, the result is not the `2.5d_factor`.
> 
> Is the result close or not? I did not go into the code details of LCN, perhaps you can leave an issue there.

非常抱歉如此打扰了，我发现他们的repo从来不解答issue才到此处提问。如果按照上述的理解来minimize，λ会在0.2左右（实际上应该是4.6左右）。所以我以为是理解出现问题

**Comment by Walter0807** [comment]
Hi, sorry for the confusion. I consulted the LCN authors and here is the update: 
- Here is the original λ computation: https://github.com/CHUNYUWANG/lcn-pose/blob/master/tools/gendb.py#L85 (used for ICCV 2019 version, fixed bounding box size for normalization). 
- In the T-PAMI version, they switched to a different computation method (pasted above).
- The two versions actually give very similar λ results.
我觉得可能是你算minimize的方式不太一样，可以看一下release版的实现看看是否有帮助。

**Comment by Walter0807** [comment]
> > > I think it's on their T-PAMI version section 6.2.2. Basically, it's just a normalizing factor between the pixel coordinates and the world coordinates.
> > 
> > 
> > Hi @Walter0807, I read through that section, but it actually explains your `DataReaderH36M`. I wonder how to obtain that factor, as it does not appear in any code scripts, thx!
> 
> Sorry, it should be in Section 6.2.1 (LCN, T-PAMI 2020). <img alt="image" width="537" src="https://github.com/Walter0807/MotionBERT/assets/25319568/a4a25bad-e323-4963-9c33-bc7512218d3a"> The 2.5d factor is the λ here.

My fault. λ (world to pixel) should be the reciprocal of `2.5d_factor` (pixel to world).

**Comment by LareinaM** [comment]
Thank you so much for your help! I figured it out now.
