### ISSUE TITLE
Cuda Out of Memory and Minimum System Specification for running 3D human Pose Estimation

### ISSUE THREAD

**Issue by leilaUEA** [Walter0807/MotionBERT#54]
Hi, 
I was trying to run the 3d pose estimation part in:
https://github.com/Walter0807/MotionBERT/blob/main/docs/pose3d.md

on both my laptop and university HPC, and I get cuda pot of memory error. I was wondering is it because of Pytorch reserving too much space (software problem) or the system resources are low.  

If I want to set up a system for 3D human pose estimation, what is the minimum system specification?( If you have tested it on a specific computer if you could give me an specification that would be great

So in summary my question is:

1) How to solve cuda out of memory error?
2) What is the minimum system specification for running and coding human 3D pose estimation?

I installed cuda toolkit 11.8 and matching pytorch on HPC, on laptop I tested on cuda 10.1

The error on laptop:
RuntimeError: CUDA out of memory. Tried to allocate 260.00 MiB (GPU 0; 3.81 GiB total capacity; 2.57 GiB already allocated; 167.81 MiB free; 2.60 GiB reserved in total by PyTorch)

The error on the HPC:

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 260.00 MiB (GPU 0; 23.65 GiB total capacity; 22.16 GiB already allocated; 20.31 MiB free; 22.80 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

torch.cuda.OutOfMemoryError: CUDA out of memory.
Tried to allocate 518.00 MiB (GPU 0; 11.17 GiB total capacity; 10.73 GiB already allocated; 228.38 MiB free; 10.79 GiB reserved in total by PyTorch)
If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  
See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Thank you very much in advance.
I look forward to hearing from you.

**Comment by Walter0807** [comment]
Hi, are you running training or inference? You could consider reducing the batch size.

**Comment by leilaUEA** [comment]
Thanks very much for your response. I was trying to run train.py according to the following instructions:
https://github.com/Walter0807/MotionBERT/blob/main/docs/pose3d.md

starting from the following command:
python train.py --config configs/pose3d/MB_train_h36m.yaml --checkpoint checkpoint/pose3d/MB_train_h36m

I changed the "args.batch_size" from its default value which is 32 to 16, 8, 4, 2 and still getting the "cuda out of memory" error:

---------------------
batch size = 32

CUDA out of memory. Tried to allocate 518.00 MiB (GPU 0; 3.82 GiB total capacity; 2.75 GiB already allocated; 103.38 MiB free; 2.79 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

---------------------

batch size = 16

CUDA out of memory. Tried to allocate 492.00 MiB (GPU 0; 3.82 GiB total capacity; 2.60 GiB already allocated; 246.25 MiB free; 2.62 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

---------------------

batch size = 8

CUDA out of memory. Tried to allocate 246.00 MiB (GPU 0; 3.82 GiB total capacity; 2.62 GiB already allocated; 215.44 MiB free; 2.69 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

---------------------

batch size = 4

CUDA out of memory. Tried to allocate 124.00 MiB (GPU 0; 3.82 GiB total capacity; 2.75 GiB already allocated; 24.19 MiB free; 2.88 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

---------------------

batch size = 2

CUDA out of memory. Tried to allocate 62.00 MiB (GPU 0; 3.82 GiB total capacity; 2.58 GiB already allocated; 59.81 MiB free; 2.79 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

---------------------

I was wondering if I change the computer this or similar programs can work or I need to change something in the code?

Thank you very much in advance

**Comment by Walter0807** [comment]
I think 3GB cuda memory might not be enough for training.Best,WentaoSent from my iPhoneOn 1 Jul 2023, at 01:41, leilaUEA ***@***.***> wrote:﻿
Thanks very much for your response. I was trying to run train.py according to the following instructions:
https://github.com/Walter0807/MotionBERT/blob/main/docs/pose3d.md
starting from the following command:
python train.py --config configs/pose3d/MB_train_h36m.yaml --checkpoint checkpoint/pose3d/MB_train_h36m
I changed the "args.batch_size" from its default value which is 32 to 16, 8, 4, 2 and still getting the "cuda out of memory" error:

batch size = 32
CUDA out of memory. Tried to allocate 518.00 MiB (GPU 0; 3.82 GiB total capacity; 2.75 GiB already allocated; 103.38 MiB free; 2.79 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

batch size = 16
CUDA out of memory. Tried to allocate 492.00 MiB (GPU 0; 3.82 GiB total capacity; 2.60 GiB already allocated; 246.25 MiB free; 2.62 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

batch size = 8
CUDA out of memory. Tried to allocate 246.00 MiB (GPU 0; 3.82 GiB total capacity; 2.62 GiB already allocated; 215.44 MiB free; 2.69 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

batch size = 4
CUDA out of memory. Tried to allocate 124.00 MiB (GPU 0; 3.82 GiB total capacity; 2.75 GiB already allocated; 24.19 MiB free; 2.88 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

batch size = 2
CUDA out of memory. Tried to allocate 62.00 MiB (GPU 0; 3.82 GiB total capacity; 2.58 GiB already allocated; 59.81 MiB free; 2.79 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

I was wondering if I change the computer this or similar programs can work or I need to change something in the code?
Thank you very much in advance

**Comment by leilaUEA** [comment]
Thank you very much for your response. 

I am trying running on rtx-6000 with batch_size=8 on the High Performance Computing (HPC) and it is running without error until now. For the personal PC, we might be able to upgrade the GPU. As we cannot use trial and error to find the required specification, I was wondering if you know the minimum GPU specification that can run the training code? If the training can be run on a PC with a better GPU, what is the GPU that you have tested running the training?
Many Thanks,
Leila
