### ISSUE TITLE
Desired Processing Speed of MotionBERT

### ISSUE THREAD

**Issue by joonjeon** [Walter0807/MotionBERT#55]
Hi!

I am interested in using the MotionBERT model for 3D human pose estimation.

At this point, I am attempting to use it for real-time pose estimation in a human-robot interaction application,
where the MotionBERT is used for transforming the 2D points to 3D space.

Here, I have set the input video size to FHD resolution (1920x1080).
When I try to deploy the model on NVIDIA Jetson TX, however, the speed is only about **2.5 FPS**,
and the speed reaches only up to **5 FPS** on a machine with NVIDIA V100 GPU... only a 2x speedup.
(As an aside I also tested out YOLOv7 on both Jetson TX and the machine with NVIDIA V100 GPU using the same input size, and there **was about 14x speedup from 5 FPS to 71 FPS.**)

Is this a normal operation?
If yes, are there any measures that I can take to speed up this model without damaging accuracy-related performance metric values?
If not, could you tell me how to fix this issue?

Thanks in advance.

**Comment by Walter0807** [comment]
Hi, thanks for your interest in our work. The inference speed should be quite fast, and the speed bottleneck is rendering for visualization. You can turn off rendering and test for the FPS.
