### ISSUE TITLE
Questions about the evaluation strategy of MotionBERT from a reader

### ISSUE THREAD

**Issue by lllluy** [Walter0807/MotionBERT#57]
Hi，

I have a question about the parameters "2.5d_factor" and "joint_2.5d_image" in the test set. I did not find the relevant information in https://github.com/CHUNYUWANG/lcn-pose#data. Therefore, I wonder how did you get it? 
Why don't the output of the model be evaluated directly with the "joint3d_images" calculation MPJPE?

Thanks in advance.

**Comment by Walter0807** [comment]
Hi, please refer to https://github.com/Walter0807/MotionBERT/issues/51 which could help.
