### ISSUE TITLE
Some sport demo relative to different clip length 

### ISSUE THREAD

**Issue by valentin-fngr** [Walter0807/MotionBERT#58]
Hi, 

Here are some 3D skeletons I extracted from sport clips (tennis). 

Tennis back hand : 
![X3D (4) (1)](https://github.com/Walter0807/MotionBERT/assets/42917280/1b8c1e19-c674-47d7-903f-df0d34ae5670)

A longer tennis sequence : 
![X3D (11)](https://github.com/Walter0807/MotionBERT/assets/42917280/d6badd03-b9ad-4f75-b37f-5b9fbffebd07)

3D representation out of an 8 min vieos
![best_federer (1)](https://github.com/Walter0807/MotionBERT/assets/42917280/ab50eb03-6657-49da-abf1-1c2ec1c3c494)

I have noticed that the longer the sequence, the better the 3D pose estimation is. 
I have also noticed that for a same clip, the angle of the 3D visualization changes with respect to the clip length. 

I observe some jittering for very short clips. 
If you guys have any idea how I can reduce that effect, please let me know. 

I have a script extracting the 2D skeleton using AlphaPose and then generating the 3D poses. 
My 2D pose estimation is very good, but I still get this jittering effect.

**Comment by Walter0807** [comment]
Hi, could you please provide more information (model, config, window size) for the results? It seems like fig 1,2,3 are not from the same model (1,2 root fixed, 3 not).

**Comment by Walter0807** [comment]
Intuitively, a longer clip length would give better results, which is also verified on Human 3.6M.

**Comment by valentin-fngr** [comment]
> Hi, could you please provide more information (model, config, window size) for the results? It seems like fig 1,2,3 are not from the same model (1,2 root fixed, 3 not).

Hi, thanks for your reply. 
You are right, GIF 1 and 2 are coming from the same "setup" while GIF 3 has been predicted with another training setup. 
Unfortunately, I do not remember the modification I did.  **Let me investigate and get back to you**. 

Is there any reason GIF 1 and 2 would have a fixed root and not 3 ?

**Comment by Walter0807** [comment]
> > Hi, could you please provide more information (model, config, window size) for the results? It seems like fig 1,2,3 are not from the same model (1,2 root fixed, 3 not).
> 
> Hi, thanks for your reply. You are right, GIF 1 and 2 are coming from the same "setup" while GIF 3 has been predicted with another training setup. Unfortunately, I do not remember the modification I did. **Let me investigate and get back to you**.
> 
> Is there any reason GIF 1 and 2 would have a fixed root and not 3 ?

It's related to the `rootrel` flag in configs.

**Comment by valentin-fngr** [comment]
So it seems that for GIF 1 and 2, I was not using tracking, even if there is only one person in my video. 
The GIF 3 was using tracking. 

Do you usually use tracking only ?

**Comment by valentin-fngr** [comment]
Hi, 

Did you update the pose3D weights for the global_lite model recently ? 
I had two version of this repo, one older one more recent. 

I had to copy the weights from the old repo to the new one to make it work on short clips :

<img src="https://github.com/Walter0807/MotionBERT/assets/42917280/9cd50139-0d7a-4933-b7e8-5f0048a71565" width="500" height="400" alt="Description of the GIF">

Important note : I have tried the two weights with the same alphapose-results.json to make sure I am testing in the same conditions for both weights.

**Comment by Walter0807** [comment]
No it has not been changed.Best,WentaoSent from my iPhoneOn 2 Jul 2023, at 06:43, valentin-fngr ***@***.***> wrote:﻿
Hi,
Did you update the pose3D weights for the global_lite model recently ?
I had two version of this repo, one older one more recent.
I had to copy the weights from the old repo to the new one to make it work on short clips :

Important note : I have tried the two weights with the same alphapose-results.json to make sure I am testing in the same conditions for both weights.
