### ISSUE TITLE
Any 3D pose evaluation scripts?

### ISSUE THREAD

**Issue by joonjeon** [Walter0807/MotionBERT#59]
Hi! I have a question in regards to evaluating performance of MotionBERT.

In terms of evaluating the 3D pose quality metric such as MPJPE of MotionBERT on the Human 3.6M Dataset,
Is there a script specifically written by the MotionBERT developers to do so?
Otherwise, if is this something that I can find in other 3D-Pose-Detection-related websites,
I would appreciate it if you could give me links to them.

Thanks in advance.

**Comment by Walter0807** [comment]
You can check this: https://github.com/Walter0807/MotionBERT/blob/main/docs/pose3d.md#running

**Comment by joonjeon** [comment]
Thank you for the reply.

However, after downloading the pre-processed H3.6M Dataset, when I attempted to run the command as instructed, the error occurs as follows:


```
Loading dataset...
Traceback (most recent call last):
  File "/home/joonjeon/MotionBERT/train.py", line 383, in <module>
    train_with_config(args, opts)
  File "/home/joonjeon/MotionBERT/train.py", line 237, in train_with_config
    train_dataset = MotionDataset3D(args, args.subset_list, 'train')
  File "/home/joonjeon/MotionBERT/lib/data/dataset_motion_3d.py", line 36, in __init__
    super(MotionDataset3D, self).__init__(args, subset_list, data_split)
  File "/home/joonjeon/MotionBERT/lib/data/dataset_motion_3d.py", line 22, in __init__
    motion_list = sorted(os.listdir(data_path))
FileNotFoundError: [Errno 2] No such file or directory: 'data/motion3d/MB3D_f243s81/H36M-SH/train'
```

Do you know where should I get the necessary file or directory?
