### ISSUE TITLE
Evaluation script doesn't seem to work properly 

### ISSUE THREAD

**Issue by joonjeon** [Walter0807/MotionBERT#61]
First of all, thank you for the reply on how to perform evaluation of MotionBERT (https://github.com/Walter0807/MotionBERT/issues/59).

However, after downloading the pre-processed H3.6M Dataset, when I attempted to run the command as instructed, the error occurs as follows:
```
Loading dataset...
Traceback (most recent call last):
  File "/home/joonjeon/MotionBERT/train.py", line 383, in <module>
    train_with_config(args, opts)
  File "/home/joonjeon/MotionBERT/train.py", line 237, in train_with_config
    train_dataset = MotionDataset3D(args, args.subset_list, 'train')
  File "/home/joonjeon/MotionBERT/lib/data/dataset_motion_3d.py", line 36, in __init__
    super(MotionDataset3D, self).__init__(args, subset_list, data_split)
  File "/home/joonjeon/MotionBERT/lib/data/dataset_motion_3d.py", line 22, in __init__
    motion_list = sorted(os.listdir(data_path))
FileNotFoundError: [Errno 2] No such file or directory: 'data/motion3d/MB3D_f243s81/H36M-SH/train'
```
Do you know where I should get the necessary file or directory?

**Comment by Walter0807** [comment]
Hi, did you slice the motion clips? (https://github.com/Walter0807/MotionBERT/blob/main/docs/pose3d.md#data)

**Comment by joonjeon** [comment]
Ahh.. Now it seems working after slicing the motion clips. Thanks.
