### ISSUE TITLE
How can I convert the results to FBX/GLB/glTF files?

### ISSUE THREAD

**Issue by Jackch56** [Walter0807/MotionBERT#63]
I want to convert the results to FBX/GLB/glTF files. I know that the result can be saved as npy file, I think I might be able to convert with this, but I can't find the solution. Could you give me some suggestions, please?

**Comment by Walter0807** [comment]
Hi, you can check this issue: https://github.com/Walter0807/MotionBERT/issues/31. They use ROMP scripts.
