### ISSUE TITLE
Where are the 2D pose inputs used in performance evaluation?

### ISSUE THREAD

**Issue by joonjeon** [Walter0807/MotionBERT#64]
Thank you for your answer to https://github.com/Walter0807/MotionBERT/issues/62.
But I am afraid I still don't get it..

Though I was able to successfully measure quality-related metrics after setting up as shown here:
https://github.com/Walter0807/MotionBERT/blob/main/docs/pose3d.md

I am not able to find where in this page mentions that the 2D pose input.

It is mentioned in the MotionBERT github page that it requires off-the-shelf 2D pose estimation results (such as those from AlphaPose) before deploying DSTFormer for 2D-to-3D lifting,
so I suppose that the instructions in the page above must be using 2D pose inputs from elsewhere.

I would like to ask how the instructions at https://github.com/Walter0807/MotionBERT/blob/main/docs/pose3d.md make use of the 2D pose inputs of a video or image sequence?
Are the 2D pose inputs automatically detected by the MotionBERT itself?
Are the 2D pose inputs embedded in the preprocessed H3.6M data?
Or is there somewhere else that the 2D pose inputs are coming?

**Comment by Walter0807** [comment]
It's in the provided H36M data.

**Comment by joonjeon** [comment]
Alright. Thanks
