### ISSUE TITLE
The code part that receives 2D poses for evaluation? List of validation set image ids in pkl file?

### ISSUE THREAD

**Issue by joonjeon** [Walter0807/MotionBERT#66]
Thank you for your answer to https://github.com/Walter0807/MotionBERT/issues/64

Now that I know that the [pkl file](https://1drv.ms/u/s!AvAdh0LSjEOlgU7BuUZcyafu8kzc?e=vobkjZ) is the source location of the ground truth 2D poses corresponding to the input images,
I would like to ask four additional things:

1. Does the [pkl file](https://1drv.ms/u/s!AvAdh0LSjEOlgU7BuUZcyafu8kzc?e=vobkjZ) contain 2D poses of only subset of Human 3.6M validation images? Or does in contain 2D poses of *WHOLE* set of Human 3.6M validation set?
2. If the pkl file contains 2D poses of only subset of Human 3.6M validation images, what is the list of images in the subset?
3. When I split the huge pkl file using `tools/convert_h36m.py`, it results in smaller individual pkl files with names `00000000.pkl`, `00000001.pkl`, `00000002.pkl`, and so on. To what Human3.6M dataset image does each of these pkl files correspond to?
4. Are the 2D pose values in the pkl file ground truths? Or are they just detections from AlphaPose? If they are detections from AlphaPose, did the AlphaPose detections make use of ground truth bounding boxes? Or did they make use of bounding boxes detected by some off-the-shelf detectors like YOLOv3?

Thank you very much in advance.

**Comment by Walter0807** [comment]
The `.pkl` file is from LCN. You may check the following links for further information:
1. https://github.com/Walter0807/MotionBERT/issues/51
2. https://github.com/CHUNYUWANG/lcn-pose/tree/master#data
3. https://github.com/Embracing/GFPose/issues/2
