### ISSUE TITLE
colab please

### ISSUE THREAD

**Issue by skyeKing** [Walter0807/MotionBERT#68]

**Comment by whatishisname** [comment]
How to do it in Google Colab:
-Download the GitHub repo in colab
-Change directory to motionbert folder
-you can use colab to download any file from the internet (training data)
-Use !python to run .py files

How to copy the repo to Google Drive from Colab:
-mount your google drive in colab
-On the left side you will see your drive folder
-Drag & drop motionbert folder into the drive folder
-go to your drive and wait & refresh the page

Please use Google search if you don't know how to do any of these steps.

**Comment by EthannHongg** [comment]
Check This Out
https://colab.research.google.com/drive/1R3G4pLixcJoM0hXsI5mEk-GhFyWsH-sC?usp=sharing
