### ISSUE TITLE
onedrive链接打不开

### ISSUE THREAD

**Issue by dddyyyplus** [Walter0807/MotionBERT#7]
请问这是为什么呀

**Comment by Walter0807** [comment]
Maybe you can use a proxy to open OneDrive. We might upload a version to other net disks for next release.

**Comment by dddyyyplus** [comment]
学长您好，我是开了代理的，google drive是可以上去的，可能onedrive还是有点问题，期待您的下一版release！


我还有一个问题想问您一下，我看了您MoCaNet的文章，想了解一些您论文中的细节问题，比如MoCaNet的输入是source和target两种2D Sequence，这个是他的二维关键点数据吗？然后网络输出的是retargeted 3D sequence，这个包含骨架的旋转信息吗？还是只有三维点的信息呀，因为我在想如果是三维点的信息的话是怎么得到良好的目标动画的呢，我最近才入门动作重定向，很冒昧打扰您了！









刘澄宇

北京邮电大学/研究生/计算机学院（国家示范性软件学院）



北京




&nbsp;
&nbsp;
&nbsp;
------------------ Original ------------------
From: &nbsp;"Wentao ***@***.***&gt;;
Date: &nbsp;Thu, Nov 24, 2022 03:51 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [Walter0807/MotionBERT] onedrive链接打不开 (Issue #7)

&nbsp;



 
Maybe you can use a proxy to open OneDrive. We might upload a version to other net disks for the next release.

**Comment by Nancy-sn** [comment]
> Maybe you can use a proxy to open OneDrive. We might upload the models to other net disks as well for the next release.

Hello, has the link been updated? I have been trying to download the processed data through your link these days, but I still can't download it.

**Comment by murphyhoucn** [comment]
I face the same problem and don't know how to solve it.
