### ISSUE TITLE
running infer_wild.py takes so much time

### ISSUE THREAD

**Issue by StrongMan988** [Walter0807/MotionBERT#70]
Hello author, first of all, thank you for your efforts. Your work is quite commendable. And then I run 'infer'_ Wild. py reasoned that a 30 second video would take 2.5 hours. I can be certain that my CPU, running memory, and GPU3070 do not occupy much performance. So come and ask if I need to change some parameters or take other measures to make my operation faster. Thank you again for your great contribution. I hope you can reply to me as soon as you see it

**Comment by Walter0807** [comment]
Rendering should be the bottleneck. Please check you matplotlib version or maybe turn off rendering.
