### ISSUE TITLE
About global trans

### ISSUE THREAD

**Issue by Yamato-01** [Walter0807/MotionBERT#77]
I want to visualize the estimated SMPL mesh according to [in-the-wild inference, MESH](https://github.com/Walter0807/MotionBERT/blob/main/docs/inference.md)
It seems that the model doesn't return  transl  and the SMPL mesh is fixed in each frame. I am confused what's the `3d-pose-results.npy` means. Alphapose 3d results or MB output?

**Comment by Walter0807** [comment]
It is the MB 3D pose output which is used to visualize the global root trajectory.
