### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by abaybektursun** [Walter0807/MotionBERT#8]
Hi, thanks for the release, looks very cool!
Can you please give me a hint on how I can utilize your pre-trained model to inference on my own video?
Given a video, do I need to run 2D pose estimation first before I can use MotionBERT? Or do you already provide that?
How should I generate 3D points on my video?
How can I get the motion embedding? I tried:
```python
E = MotionBERT.get_representation(x)
```
but `get_representation` does not exist!
Thank you!

If you could just give me high level hints I would appreciate it! Thanks!

**Comment by Walter0807** [comment]
Hi, thanks for your interest in our work! We have updated the docs for in-the-wild inference.
