### ISSUE TITLE
How to get J_regressor_h36m_correct.npy

### ISSUE THREAD

**Issue by buptxyb666** [Walter0807/MotionBERT#80]
I have some problems when processing AMASS data, the J_regressor_h36m_correct.npy obtained from https://github.com/hongsukchoi/Pose2Mesh_RELEASE/tree/master/data/Human36M cannot be read by np.load(), can you provide a available J_regressor_h36m_correct.npy for me? Furthermore, i found there is no 2D data used in pre-train stage, which is inconsistent with the paper?

**Comment by ShirleyMaxx** [comment]
Hi, for the first question, I've just downloaded the `J_regressor_h36m_correct.npy` file from [https://github.com/hongsukchoi/Pose2Mesh_RELEASE/tree/master/data/Human36M](https://github.com/hongsukchoi/Pose2Mesh_RELEASE/tree/master/data/Human36M) and it can be correctly loaded by `np.load()`, the numpy version I used is `1.21.5`. Maybe you could have another try.

**Comment by Walter0807** [comment]
> Furthermore, i found there is no 2D data used in pre-train stage, which is inconsistent with the paper?

We use 2D dataset InstaVariety.

**Comment by buptxyb666** [comment]
> Hi, for the first question, I've just downloaded the `J_regressor_h36m_correct.npy` file from https://github.com/hongsukchoi/Pose2Mesh_RELEASE/tree/master/data/Human36M and it can be correctly loaded by `np.load()`, the numpy version I used is `1.21.5`. Maybe you could have another try.

It still doesn't work with numpy 1.21.5.

**Comment by ShirleyMaxx** [comment]
> > Hi, for the first question, I've just downloaded the `J_regressor_h36m_correct.npy` file from https://github.com/hongsukchoi/Pose2Mesh_RELEASE/tree/master/data/Human36M and it can be correctly loaded by `np.load()`, the numpy version I used is `1.21.5`. Maybe you could have another try.
> 
> It still doesn't work with numpy 1.21.5.

It's weird😕 Could you please paste the error information here?

**Comment by dajiaohuang** [comment]
install human_motion_prior from github instead of pypi
