### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/mesh/smpl_mean_params.npz'

### ISSUE THREAD

**Issue by KenAdamJoseph** [Walter0807/MotionBERT#81]
when i run the following code to Evaluate h36m dataset, cant find the file smpl_mean_params.npz.
python train_mesh.py --config configs/mesh/MB_train_h36m.yaml --evaluate checkpoint/mesh/MB_train_h36m/best_epoch.bin
FileNotFoundError: [Errno 2] No such file or directory: 'data/mesh/smpl_mean_params.npz'

Additionally,I search the filename h36m_mean_smpl.npz in the code,and it is not used in the code.

**Comment by KenAdamJoseph** [comment]
should i download this file following https://github.com/nkolot/SPIN/tree/master/data  ?

**Comment by Walter0807** [comment]
Fixed, please check again. Thank you!
