### ISSUE TITLE
Questions about the model used to extract the 2D keypoints.

### ISSUE THREAD

**Issue by BellXP** [Walter0807/MotionBERT#83]
In docs/inference.md, the 2D keypoints extracted by the Fast Pose model trained on the Halpe dataset seem to have 26 keypoints, which conflict with the 17 keypoints used in MotionBERT's config file.

Is there any wrong with the model used to extract the 2D keypoints?

**Comment by whatishisname** [comment]
There is nothing wrong with the model (convert to human3.6 -> reorder & ignore extra keypoints)
If you check def halpe2h36m(x) inside \lib\data\dataset_wild.py file you will see how to convert from Halpe to human3.6 keypoints.
if you use mmpose or yolov8 you can check def coco2h36m(x) inside \lib\data\dataset_action.py
or just make sure to export only the 17 keypoints in the correct order when you run the 2d pose estimation model.

**Comment by Walter0807** [comment]
We convert Halpe (26 keypoints) to Human 3.6M (17 keypoints).
