### ISSUE TITLE
Can I Use other methods to get 2Dpose such as MMPose

### ISSUE THREAD

**Issue by Xushuolin** [Walter0807/MotionBERT#88]
Hello! great work, can I use the method in MMPose without applying the alpha pose to get the 2Dpose?

**Comment by whatishisname** [comment]
Yes, you can do that.
I tried Yolov8 and MMpose
but They both use Coco's keypoints so make sure to fix keypoints order and add the missing one
Check out def coco2h36m(x) inside lib\data\dataset_action.py file on how to convert from coco to human3.6 keypoints.

**Comment by ethan-hibikirun** [comment]
@whatishisname can u plz provide

**Comment by Walter0807** [comment]
Thanks for your interest. MotionBERT has been integrated into MMPose with their 2D pose estimators: https://github.com/open-mmlab/mmpose/tree/main/configs/body_3d_keypoint/motionbert

**Comment by vuxminhan** [comment]
@Walter0807 I would like to as is there any other 2D model intergrated, if so which one has yield the best result for being input of 3D model. Thanks in advance
