### ISSUE TITLE
3D keypoint information and 2D keypoint information are not aligned

### ISSUE THREAD

**Issue by jdyjjj** [Walter0807/MotionBERT#91]
Thank you very much for your amazing work. I encountered some issues while using this project. My pose keypoint information is extracted based on an alphapose. When I run infer_wild.py, the 3D keypoint information and 2D keypoint information are not aligned. For example, I have 233 2D keypoints, but the generated 3D keypoints have 234. May I ask why this is and how can I do it so that the 3D keypoints and 2D keypoints can be aligned?

**Comment by Haixin-Gong** [comment]
I met the same issue. Have you solved the problem? Actually the length of 2D keypoints is identical with the input video frames length while the 3D keypoints seem to be wrongly aligned. I'd appreciate it  for your help.
