### ISSUE TITLE
What is the third channel for 2D pose input?

### ISSUE THREAD

**Issue by pha123661** [Walter0807/MotionBERT#93]
Thanks for your great work!
I would like to know what the third channel of 2D pose input stands for? Is it the output confidence score of the pose estimators?

```
x: 2D skeletons 
    type = <class 'torch.Tensor'>
    shape = [batch size * frames * joints(17) * channels(3)]
```

**Comment by whatishisname** [comment]
Yes, it is the output confidence score of the 2d pose estimator.

**Comment by Walter0807** [comment]
Thanks for your interest! It is the confidence of the 2D joint.
