### ISSUE TITLE
Where can I get the finetuned version with 16.9 mm mpjpe

### ISSUE THREAD

**Issue by ethan-hibikirun** [Walter0807/MotionBERT#95]
saw it here https://paperswithcode.com/paper/motionbert-unified-pretraining-for-human#code but can't find the model. Is this 3D Pose (H36M-SH, ft)? but why are the metrics different

**Comment by Walter0807** [comment]
I think it is the result of using ground-truth 2D keypoint as input. You can train it by setting `gt_2d` as true in the training configs.
