### ISSUE TITLE
Question aboud the abnormal numerical value of the root node of the non-lite model

### ISSUE THREAD

**Issue by AlexiaAnn** [Walter0807/MotionBERT#99]
The values ​​of the root node output by the non-lite(pose3d/FT_MB_release_MB_ft_h36m/best_epoch.bin) model are very small, and it appear to be stationary in space.
left:non-lite right:lite
![motionbert](https://github.com/Walter0807/MotionBERT/assets/20398421/a6f55c70-7fb3-4411-99f7-6e74dabf1f7a)

**Comment by Walter0807** [comment]
It is related to the `rootrel` config during finetuning.

**Comment by AlexiaAnn** [comment]
So I want to use the non-lite version while outputting the correct root value, how to do it. I have turned off rootrel in the configuration file and rootrel in the program. The values ​​in my picture above are directly given by the model without post-processing.
